service: s3-document-uploader-pre-signed

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    BUCKET_NAME: s3-upload-bucket-pooja
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::s3-upload-bucket-pooja/uploads/*
functions:
  getSignedUrl:
    handler: handlers/s3-upload-pre-signed.handler
    layers: arn:aws:lambda:ap-south-1:154764642821:layer:ses-email:1
    events:
      - http:
          path: generate-url
          method: post

