service: s3-csv-processor
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    TABLE_NAME: ${env:TABLE_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
            - lambda:*
            - dynamodb:*
          Resource: "*"

functions:
  processCsv:
    handler: handlers/process-csv.handler
    layers: arn:aws:lambda:ap-south-1:154764642821:layer:ses-email:1
    events:
      - s3:
          bucket: s3-upload-bucket-pooja
          event: s3:ObjectCreated:*
          existing: true


resources:
  Resources:
    CsvDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dotenv-plugin
